CREATE TABLE IF NOT EXISTS users (
	user_id VARCHAR(50) PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	second_name VARCHAR(50) NOT NULL,
	birth_date TIMESTAMP NOT NULL,
	login VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(255) NOT NULL
)

GO